spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
  flyway:
    url: jdbc:postgresql://localhost:5433/users
  data:
    mongodb:
      host: localhost

logging:
  level:
    org.flywaydb: TRACE
    org.hibernate.SQL: TRACE