server:
  address: 127.0.0.1

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/users
  flyway:
    url: jdbc:postgresql://postgres:5432/users
  data:
    mongodb:
      host: mongo
  kafka:
    bootstrap-servers: kafka:9092

