spring:
  datasource:
    url: jdbc:postgresql://postgres-users:5432/users
  flyway:
    url: jdbc:postgresql://postgres-users:5432/users
  data:
    mongodb:
      host: mongo
  kafka:
    bootstrap-servers: kafka:9092

