server:
  port: 8081

spring:
  profiles:
    active: local
  datasource:
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: postgres_password
    locations: classpath:db/migration/main

password:
  hashing:
    salt: "2b7e151628aed2a6abf7158809cf4f3c"

validation:
  emailRegex: "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$"
