spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
  flyway:
    url: jdbc:postgresql://localhost:5433/users
  data:
    mongodb:
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.flywaydb: TRACE
    org.hibernate.SQL: TRACE
    org.apache:
      kafka:
        clients:
          producer:
            internals: TRACE