spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/main
logging:
  level:
    org.flywaydb: TRACE
    org.hibernate.SQL: TRACE